Layout/LineLength:
  Max: 120
  Exclude:
    - 'legion-cache.gemspec'
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/*/**.rb'
Metrics/AbcSize:
  Max: 18
Style/Documentation:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false